from __future__ import annotations

from app.web import runtime_process_control as web_runtime_process_control
from app.web import runtime_process_history as web_runtime_process_history
from app.web import runtime_process_parsing as web_runtime_process_parsing
from app.web import runtime_process_progress as web_runtime_process_progress


redact_command_secrets = web_runtime_process_parsing.redact_command_secrets
is_nmap_command = web_runtime_process_parsing.is_nmap_command
is_nuclei_command = web_runtime_process_parsing.is_nuclei_command
is_tshark_passive_capture_command = web_runtime_process_parsing.is_tshark_passive_capture_command
sample_process_tree_activity = web_runtime_process_parsing.sample_process_tree_activity
process_tree_activity_changed = web_runtime_process_parsing.process_tree_activity_changed
coerce_float = web_runtime_process_progress.coerce_float
format_duration_label = web_runtime_process_progress.format_duration_label
normalize_progress_source_label = web_runtime_process_progress.normalize_progress_source_label
build_process_progress_payload = web_runtime_process_progress.build_process_progress_payload
process_progress_adapter_for_command = web_runtime_process_progress.process_progress_adapter_for_command
estimate_remaining_from_percent = web_runtime_process_progress.estimate_remaining_from_percent
extract_progress_line = web_runtime_process_progress.extract_progress_line
extract_nmap_progress_message = web_runtime_process_progress.extract_nmap_progress_message
extract_nuclei_progress_from_text = web_runtime_process_progress.extract_nuclei_progress_from_text
extract_tshark_passive_progress = web_runtime_process_progress.extract_tshark_passive_progress
update_process_progress = web_runtime_process_progress.update_process_progress
update_nmap_process_progress = web_runtime_process_progress.update_nmap_process_progress
extract_nmap_progress_from_text = web_runtime_process_progress.extract_nmap_progress_from_text
parse_duration_seconds = web_runtime_process_progress.parse_duration_seconds
list_processes = web_runtime_process_history.list_processes
process_history_records = web_runtime_process_history.process_history_records
normalize_process_timestamp_to_utc = web_runtime_process_history.normalize_process_timestamp_to_utc
process_timestamp_utc_candidates = web_runtime_process_history.process_timestamp_utc_candidates
normalize_process_time_range_to_utc = web_runtime_process_history.normalize_process_time_range_to_utc

register_job_process = web_runtime_process_control.register_job_process
unregister_job_process = web_runtime_process_control.unregister_job_process
job_active_process_ids = web_runtime_process_control.job_active_process_ids
start_process_retry_job = web_runtime_process_control.start_process_retry_job
retry_process = web_runtime_process_control.retry_process
build_process_retry_plan = web_runtime_process_control.build_process_retry_plan
split_process_retry_targets = web_runtime_process_control.split_process_retry_targets
signal_process_tree = web_runtime_process_control.signal_process_tree
kill_process = web_runtime_process_control.kill_process
clear_processes = web_runtime_process_control.clear_processes
close_process = web_runtime_process_control.close_process
get_process_output = web_runtime_process_control.get_process_output
list_jobs = web_runtime_process_control.list_jobs
get_job = web_runtime_process_control.get_job
stop_job = web_runtime_process_control.stop_job
tool_execution_profile = web_runtime_process_control.tool_execution_profile
resolve_process_timeout_policy = web_runtime_process_control.resolve_process_timeout_policy
ensure_process_tables = web_runtime_process_control.ensure_process_tables
count_running_or_waiting_processes = web_runtime_process_control.count_running_or_waiting_processes
